### ISSUE TITLE
Feature Request: Identify secrets by sub-group in a KeePass database

### ISSUE THREAD

**Issue by NJK-HOME** [JustinGrote/SecretManagement.KeePass#10]
If I have a "test" entry at the root and another "test" entry in sub-group called "Computers" it complains that there are duplicates.  Is there any way you can provide identification of the secret by the sub-group it lives in?  Even if there are no duplicates - this would be a nice feature to have it identify secrets by location for those of us that organize using sub-groups in a KeePass database.

Thanks
NK

**Comment by JustinGrote** [comment]
Yes, it's on the roadmap to make it so that key names will include their folder names, e.g. Financial/Banks/MyBankSecret. The structure of the Keepass API makes this a little difficult to do but it is feasible.

**Comment by JustinGrote** [comment]
Implemented in #14

**Comment by NJK-HOME** [comment]
Thank you!
