### ISSUE TITLE
Unable to remove secret

### ISSUE THREAD

**Issue by ReneSchumacher** [JustinGrote/SecretManagement.KeePass#17]
I'm using v0.0.9.3 of the module and tried to remove a secret from the KeePass database. This fails with error message

`Remove-Secret: Unable to remove secret {mySecret} from vault {myVault}`

Adding and reading secrets works fine. However, running Set-Secret for the same secret twice results ins a duplicate entry. Thus, I wanted to remove the secret first, which isn't working. Is there any way to get more information about the root cause here?

**Comment by JustinGrote** [comment]
@ReneSchumacher The current logic may not find the existing secret based on how pathing works in Keepass. I thought we had test coverage for this but I'll look into it when I get a chance.

Try adding `ShowFullPath=$true` to your vault parameters and see if it still happens with fully qualified names.

**Comment by ReneSchumacher** [comment]
Nope, doesn't change anything. My database does not have any groups, thus, all secrets are stored at the root level. I tried adding a secret to a group and Get-SecretInfo does indeed show the full path now. Yet, I still get the same error :-(

**Comment by trir262** [comment]
I'll take a look. Probably will start by defining a 'default' set of tests prior to handling this issue.

**Comment by JustinGrote** [comment]
@ReneSchumacher so this is a bit tricky, I'm going to work out a way to provide the UUID of the key you want to delete if an ambiguity exists. I'm also waiting on the next RC release for the metadata feature to make this more structured.

For now I'm going to push a change that prevents secret clobbering. The error you are getting is a "generic" one but probably when you are doing remove-secret you have ambiguous secrets, but the way that Secret Management handles errors, it hides it and you have to look at the innerexception of the error to see that more specific error rather than the generic "Unable to remove secret".

I plan to push a PR to surface errors more cleanly as non-terminating errors.

**Comment by ReneSchumacher** [comment]
Thanks, @JustinGrote. Just to clarify: I cannot remove any secret. I deleted the duplicate secrets using KeePass and tried again but the result is always the same.

Still looking forward to the new version and will try again.

**Comment by JustinGrote** [comment]
I'll evaluate the removal logic as well before I close this issue with a PR

**Comment by JustinGrote** [comment]
@ReneSchumacher I updated the error exposure to make it more clear what is going on.

I will also be adding a secretinfo filter logic soon to allow you to specify a secret by UUID to resolve this issue.

**Comment by JustinGrote** [comment]
@ReneSchumacher This should be fixed in `0.0.9.4`, let me know if it's fixed so I can close the issue. As far as the secretinfo filter logic I'm waiting for the metadata feature to be added upstream to secretmanagement before purposing it.

**Comment by ReneSchumacher** [comment]
Great, will test today and give you feedback!

**Comment by ReneSchumacher** [comment]
@JustinGrote Removing secrets now works. There's just one more small thing: I'm trying to use KeePass in a non-interactive environment so I cannot react to any confirmation prompts. When trying to remove a secret from a database that doesn't have a recycle bin group, I am prompted to confirm deletion. I've seen that the underlying PoshKeePass does have a NoRecycle switch for this purpose but I'm unable to specify this on the command line (probably due to the limited options allowed by the secret management framework).

Would it be feasible to add an option similar to ShowRecycleBin to the vault parameters to handle this? Something like UseRecycleBin?

**Comment by JustinGrote** [comment]
@ReneSchumacher I'll close this issue and put your request on the roadmap
