### ISSUE TITLE
Get-Secret Does Not Pull Updated Password from KeePass DB

### ISSUE THREAD

**Issue by magyarka** [JustinGrote/SecretManagement.KeePass#28]
**_NOTE: Not sure if this is an issue with the SecretManagement.KeePass module or the larger Microsoft.PowerShell.SecretManagement module._**

**Situation:**
- Start PowerShell session that has a KeePass vault registered already
- Store the credentials for one of the KeePass secrets as a variable
Example:
`$testCreds = Get-Secret -Vault testVault -Name 'test-creds'`
- Successfully connect to remote system with saved credential
- Update password for 'test-creds' in the KeePass database and save
- Attempt to update stored credential in PowerShell session by running the **Get-Secret** command again
Example:
` $testCreds = Get-Secret -Vault testVault -Name 'test-creds'`
- Unable to authenticate with remote system using $testCreds
- Close PowerShell session
- Open new PowerShell session
- Store the credentials again
Example:
` $testCreds = Get-Secret -Vault testVault -Name 'test-creds'`
- Successfully connect to remote system with saved credential

**Comment by JustinGrote** [comment]
Due to the nature of how keepass works, once you unlock a vault, that vault is persisted in memory for performance, otherwise you have to close and open the vault every single action. I will add a command `Refresh-KeepassSecretVault` that will remove the connection and allow you to get refreshed info.

**Comment by JustinGrote** [comment]
I figured out a way to have the refresh work  automatically, since keepass persists the database hash of the last on-disk DB it saved.

**Comment by sba923** [comment]
@JustinGrote I faced that issue again today with version 0.9.1.3 of the module, and version 1.1.0 of `Microsoft.PowerShell.SecretManagement`, after I had to change my AD password (company policy).

Seems I had to close all PowerShell instances (including VScode extension ones) to get a script of mine that uses `Get-Secret` to work properly.

Does this ring a bell?
