### ISSUE TITLE
test functions not working?

### ISSUE THREAD

**Issue by maroliict** [JustinGrote/SecretManagement.KeePass#32]
Hi,
Thanks for your contribution to security. 
I am testing right now the functionality to use a keepass database for storing sensitive accounts using SecretManagement module.
I am facing a few strange things:

1) register-secretvault -name 'test' -modulename 'SecretManagement.Keepass' -vaultparameters @{
path= c:\blah\blah.kdbx} 
If done, no error or whatever is shown, so assuming it is working
get-secretvault shows vault Test

After this running test-secretvault 'test' does return an error indicating that I need to add the Path Vault variable to your keepass database

Forewards this message is shown at every step. So cannot retrieve any password from my safe.

Am i missing something?

Running:
SecretManagement RC1
Keepass 2.47
SecretManagement.keepass 0.0.9.4

**Comment by JustinGrote** [comment]
Hi Maroliict,

Can you try using Register-KeePassSecretVault? It provides much better sanity checking. 

The secret management team on-purpose decided that register-secretvault will not actually validate your settings for offline scenarios. I don't agree with it but it is what it is :)

**Comment by maroliict** [comment]
I saw that in your comments to the module. Thanks. I will look into it tomorrow during sprint planning :)

**Comment by JustinGrote** [comment]
@maroliict since I can't reproduce I'll go ahead and close this but go ahead and request reopening if you still have the issue.
