### ISSUE TITLE
Syntax question on VerbosePreference in Test-SecretVault

### ISSUE THREAD

**Issue by DonPwrShellHunt** [JustinGrote/SecretManagement.KeePass#33]
The following code snippet is from Test-SecretVault.ps1

```powershell
    if ($AdditionalParameters.Verbose) {
        $VerbosePreference = $true
    }
```

I think the proper value would be 'Continue' rather than $true, right?

Interactively I get the following>

PS> ```$VerbosePreference = $true```
MetadataError: Cannot convert value "True" to type "System.Management.Automation.ActionPreference". Error: "Invalid cast from 'System.Boolean' to 'System.Management.Automation.ActionPreference'."

**Comment by JustinGrote** [comment]
@DonPwrShellHunt you are correct! This was a flowdown preference from secretmanagement I only gave a half-effort to, I'll put this on the to-fix list.
