### ISSUE TITLE
Possible issue with #requires in secretmanagement.keepass.extension.psm1

### ISSUE THREAD

**Issue by salbeck** [JustinGrote/SecretManagement.KeePass#4]
I'm unable to register a vault using the module secretmanagement.keepass.extension, it claims that the PoshKeepass module is not loaded.
If I explicitly import the module with verbose output, I can see that PoshKeepass is indeed imported but is apparently not accepted by the #requires statement in the psm1-file. If I comment out the #requires line and add 'Import-Module -Name "$pscriptroot\..\poshkeepass\poshkeepass.psd1" -Force', everything works as expected. Tested in WindowsPowershell 5.1 and Powershell 7 on Windows

**Comment by JustinGrote** [comment]
@salbeck thanks I'll take a look. I use an internal version of PoshKeePass because I had to modify it to make it work with Secret Management, I may just throw it out and go straight to the native DLLs directly :)

**Comment by JustinGrote** [comment]
Fixed in d211331054bb3e66f9a3360edcb517dc347e9f38 and pushed as 0.0.4.4
