### ISSUE TITLE
Keyfile on UNC path causes error

### ISSUE THREAD

**Issue by tsmarvin** [JustinGrote/SecretManagement.KeePass#44]
Hello,

Thank you for the great module/extension! Unfortunately I believe I may have found a bug.

If you register a vault and use a UNC KeyPath you will receive an error when trying to unlock the vault. Move the key file to the local disk and the error goes away. 

I am able to successfully open the database with a UNC key file using the regular keepass client. I'm running Microsoft.PowerShell.SecretManagement v0.9.1

# Replication Steps:
```powershell
Import-Module 'SecretManagement.KeePass'

Register-SecretVault -Name 'TestVault' -ModuleName 'SecretManagement.Keepass' -VaultParameters @{
	Path              = '\\Server.FQDN.com\Share\Folder\TestVault.kdbx'
	UseMasterPassword = $true
	KeyPath           = '\\Server.FQDN.com\Share\Folder\TestVault.keyx'
}
Test-SecretVault -Name 'TestVault' -Verbose # Enter password at prompt
# Receive Errors

# Cleanup vault and re-register
UnRegister-SecretVault -Name 'TestVault'

Register-SecretVault -Name 'TestVault' -ModuleName 'SecretManagement.Keepass' -VaultParameters @{
	Path              = '\\Server.FQDN.com\Share\Folder\TestVault.kdbx'
	UseMasterPassword = $true
	KeyPath           = 'C:\TestVault.keyx'
}
Test-SecretVault -Name 'TestVault' -Verbose # Enter password at prompt
# Works without error.
```

# Examples
## UNC Path
![KeyFile on UNC path causes error](https://user-images.githubusercontent.com/57049894/112424303-684fcf80-8cf1-11eb-86f8-7776c3570204.png)

## Local Path
![KeyFile local](https://user-images.githubusercontent.com/57049894/112424321-70a80a80-8cf1-11eb-95eb-08cbd79a4b53.png)

I believe I've narrowed down the issue to the  [KcpKeyFile]::new() call on [line 76](https://github.com/JustinGrote/SecretManagement.KeePass/blob/db677deec0551a1850792b5d1bad45a22facd972/SecretManagement.KeePass/SecretManagement.KeePass.Extension/Public/Connect-KeepassDatabase.ps1#L76) of Connect-KeePassDatabase but have not had time to research further tonight. 

I would love to help contribute to the fix (if you need/want help).

Thank you

**Comment by JustinGrote** [comment]
Sure! Pull Requests are always accepted. As a workaround you can map a drive to the UNC path. If I have some time I'll investigate but it's probably something in how resolve-path handles UNC paths.

**Comment by tsmarvin** [comment]
Hello! My [pull request](https://github.com/JustinGrote/SecretManagement.KeePass/pull/45) is ready for review whenever you have time. 
Thank you!

**Comment by JustinGrote** [comment]
@tsmarvin I haven't forgotten about this, I hope to carve out time to review tomorrow.
