### ISSUE TITLE
Test files in public folder cause error on import.

### ISSUE THREAD

**Issue by tsmarvin** [JustinGrote/SecretManagement.KeePass#47]
Hello again!

I believe I've discovered another minor issue. The public test files under `SecretManagement.KeePass\SecretManagement.KeePass.Extension\Public\*.Tests.ps1` cause errors during module import.

I am installing the module by downloading the repository from github (not the PSGallery). Using import-module on the most recent commit to main (11d45c7dafbb3f370521525ee411a9ba9dbdd684) causes this error:
![image](https://user-images.githubusercontent.com/57049894/115131431-f21b5180-9fac-11eb-95be-a4e42908323b.png)

I am able to work around the problem by simply removing the `Public\*.Tests.ps1` files and re-importing.

Thanks again for all your hard work!

**Comment by JustinGrote** [comment]
Good catch! I recently upgraded to press so the module loader may have forgotten to exclude the unit tests there.

**Comment by JustinGrote** [comment]
Fixed ab83ff6c8476312abbaae300b23c6f02687af10e and released as beta5

**Comment by tsmarvin** [comment]
Thanks again!
