### ISSUE TITLE
UNC path to the vault database does not work. 

### ISSUE THREAD

**Issue by manojpotluri** [JustinGrote/SecretManagement.KeePass#52]
I created a Vault database file on a windows share and tried to register the vault with a unc path and it fails to register.

**Comment by JustinGrote** [comment]
Hi @manojpotluri,

can you please provide more information, such as the logs or a specific screenshot of the message when it fails to register?

In general UNC paths are not supported currently but they may work in some circumstances, I'd recommend you map a drive and see if that works.

**Comment by manojpotluri** [comment]
Hello @JustinGrote 

Here is the error i am seeing when i try to register a test vault database created on a share location. 

![image](https://user-images.githubusercontent.com/453395/118050872-b5d9d780-b345-11eb-8676-e5adecb88ed3.png)

I tried the Mapped Drive suggestion as well and it errors out too 
![image](https://user-images.githubusercontent.com/453395/118051373-7f508c80-b346-11eb-9c31-2d2d6cacc6dc.png)

appreciate you taking time looking into this. 

Thanks,
Manoj.

**Comment by JustinGrote** [comment]
This looks like something that would be deeper into SecretManagement itself, not my extension. Can you provide the output of 
`$error | export-clixml $home\desktop\error.clixml` after running the command and attach the clixml to this issue?

**Comment by manojpotluri** [comment]
Attaching the Zipped error.clixml file here.  please let me know if you need more information. 
[error.zip](https://github.com/JustinGrote/SecretManagement.KeePass/files/6469364/error.zip)

**Comment by JustinGrote** [comment]
I don't think your system is fully loading the module correctly, your second error is:
![image](https://user-images.githubusercontent.com/15258962/118052344-68ef0480-b337-11eb-8412-66caefc0da27.png)
and the details are:
`Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.`

It looks like you're doing this on Powershell 5.1, have you tried it in Powershell 7?

**Comment by manojpotluri** [comment]
Hello @JustinGrote  
yes i am using powershell 5.1 on a windows 2016 datacenter server, i will try to install PowerShell 7 and see if works. 

Thanks,
Manoj.

**Comment by manojpotluri** [comment]
Hello @JustinGrote 
I installed PowerShell version 7 and tried to register a vault with a shared location and it worked :) . 

Screenshot: 
 
![image](https://user-images.githubusercontent.com/453395/118145154-e9af0e80-b3d2-11eb-8c6f-d27c6a78a89d.png)

![image](https://user-images.githubusercontent.com/453395/118145240-051a1980-b3d3-11eb-8783-e158613d225e.png)

Thanks for your help in resolving this issue. 

Thanks,
Manoj.
