### ISSUE TITLE
Design questions before contributing

### ISSUE THREAD

**Issue by Callidus2000** [JustinGrote/SecretManagement.KeePass#58]
Hi,
I'd like to contribute to your project and I've got two design questions before starting the fork and the coding:
- Would it be ok to add PSFramework as a dependency? The logging framework would be helpful with the runspace model of the new SecretManagement.
- Which branch should be used as a starting point?

Those are the things I'm missing and therefore would like (to try) to add:
- Setting secrets
- Make use of field references
- Speeding up the Get-Secret algorithm (as getting a secret from my default database needs 1.9sec instead 230ms when using the original PoSHKeepass

**Comment by JustinGrote** [comment]
Hello!

Thanks for your interest. The secretManagement/1.1.0 branch incorporates the new runspace functionality, I haven't had a chance to get back to it for a while to make sure it is stable.

PSFramework would be fine as a dependency if it adds appropriate value as you mention.

**Comment by Callidus2000** [comment]
Hi,
that's great. Now I'll see how far I get with my points. The logging framework is already implemented (search'n'replace is easy going for this ;-))

Just as an example here is an excerpt of the auto-generated CSV logfile parsed and piped into Out-GridView from running the pester-tests:
![image](https://user-images.githubusercontent.com/73584079/127146946-073faff8-f450-4ef9-8a7b-cf916aa1a124.png)
