### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spotlesscoder** [JustinGrote/SecretManagement.KeePass#70]
Hello,

what license are the resources in this repo under?

**Comment by JustinGrote** [comment]
MIT, sorry I'll get that added.

**Comment by CodingSpiderFox** [comment]
thx :)

**Comment by JustinGrote** [comment]
Derp, thanks

**Comment by JustinGrote** [comment]
Closed [cb0ddb3](https://github.com/JustinGrote/SecretManagement.KeePass/commit/cb0ddb3355b3e14c672679d687bbd8e5f5979bdf)
