### ISSUE TITLE
Opening keepass with keyfile does not work: Composite Key is invalid although it is correct

### ISSUE THREAD

**Issue by trir262** [JustinGrote/SecretManagement.KeePass#8]
My environment:
* KeePass 2.43
* Powershell 7
* SecretManagement.Keepass 0.0.9.2

I found an issue when opening a keepass file with keyfile.
The private function Connect-KeePassDatabase tests a variable $KeyFile but that is not set anywhere in the function.

Example keepass & keyfile added
[dbwithkeyfile.zip](https://github.com/JustinGrote/SecretManagement.KeePass/files/5817309/dbwithkeyfile.zip)

**Comment by JustinGrote** [comment]
Haven't actually tested the keyfile and usewindowsaccount fully yet, not surprised. I'll look into this.

**Comment by trir262** [comment]
got it working, was just a typo: keyfile should be keypath

**Comment by JustinGrote** [comment]
@trir262 I plan to provide a Get-KeePassParams or something like that to produce an object to clearly structure the keyvault options since there's basically zero feedback.

@paulhigin another real-world user example of what I'm talking about :)

**Comment by trir262** [comment]
I would think that the VaultParameters in Register-SecretVault would need to have the necessary information, like 'MasterPassword=$true' or 'KeyFileLocation=path', no?
That way, both test-secretvault and get-secret can rely on that data to do their correct handling.

Test-SecretVault in itself can also - like you did - store a module script variable to store sensitive data like the credential password, required key, ....

Or am I missing something else?
